---
title: "Untitled"
author: "Aditya Samaroo"
date: "4/3/2020"
output: html_document
---

```{r setup, include=FALSE}
require(readr)
require(ggplot2)
require(stringr)
require(ggmap)
require(maps)
require(fiftystater)
require(tidyverse)
require(RColorBrewer)
```

```{r}
asthma1 <- read_csv("data_210354.csv")
asthma2 <- read_csv("data_210457.csv")
asthma <- rbind(asthma2, asthma1)
asthma <- asthma[-c(5)]
```

```{r echo=TRUE}
states <- map_data("state") 
tidy_asthma <- asthma %>%
  mutate(Year_Group = cut(Year, breaks = c(seq(1998, 2016, by = 2)))) %>%
  filter(Value != "Data Not Collected" & Value != "Suppressed") %>%
  mutate(New_Value = as.numeric(str_replace(Value, "%",""))) %>% 
  mutate(State = tolower(State)) %>%
  group_by(stateFIPS,State, Year_Group, `Age Group`) %>%
  summarise(AVG_Value = mean(New_Value)) %>% 
  inner_join(states, by=c("State" = "region"))
```

```{r}
tidy_asthma_shiny <- asthma %>%  
  filter(Value != "Data Not Collected" & Value != "Suppressed") %>% 
  mutate(State = tolower(State)) %>%
  inner_join(states, by=c("State" = "region"))
```

```{r}
tidy_asthma1 <- tidy_asthma %>% filter(Year_Group == "(1998,2000]")
tidy_asthma2 <- tidy_asthma %>% filter(Year_Group == "(2000,2002]")
tidy_asthma3 <- tidy_asthma %>% filter(Year_Group == "(2002,2004]")
tidy_asthma4 <- tidy_asthma %>% filter(Year_Group == "(2004,2006]")
tidy_asthma5 <- tidy_asthma %>% filter(Year_Group == "(2006,2008]")
tidy_asthma6 <- tidy_asthma %>% filter(Year_Group == "(2008,2010]")
tidy_asthma7 <- tidy_asthma %>% filter(Year_Group == "(2010,2012]")
tidy_asthma8 <- tidy_asthma %>% filter(Year_Group == "(2012,2014]")
tidy_asthma9 <- tidy_asthma %>% filter(Year_Group == "(2014,2016]")
```

```{r}
asthma %>%
  mutate(Year_Group = cut(Year, breaks = c(seq(1998, 2016, by = 2)))) %>%
  filter(Value != "Data Not Collected" & Value != "Suppressed") %>%
  mutate(New_Value = as.numeric(str_replace(Value, "%",""))) %>%
  group_by(stateFIPS,State, Year_Group, `Age Group`) %>%
  summarise(AVG_Value = mean(New_Value)) %>%
  ggplot() + geom_boxplot(aes(Year_Group, AVG_Value, color = `Age Group`), alpha = 0.4) +
  theme_minimal() + labs(x = "", 
                         y = "Average %", 
                         title = "Average % of Population with Asthma")
```

```{r}
boxplot <- asthma %>%
  filter(Value != "Data Not Collected" & Value != "Suppressed") %>%
  mutate(New_Value = as.numeric(str_replace(Value, "%",""))) %>%
  group_by(State, Year, `Age Group`) %>%
  summarise(AVG_Value = mean(New_Value)) %>%
  ggplot() + geom_boxplot(aes(x = as.factor(Year), 
                              y = AVG_Value, 
                              color = `Age Group`), 
                          alpha = 0.4) +
  theme_minimal() + labs(x = "Year", 
                         y = "Average Percentage", 
                         title = "Average % of Population with Asthma by Year")

ggsave(boxplot, filename = "boxplot_asthma.png", width = 15)
```

```{r}
asthma %>%
  filter(Value != "Data Not Collected" & Value != "Suppressed") %>%
  mutate(New_Value = as.numeric(str_replace(Value, "%",""))) %>%
  group_by(State, `Age Group`) %>%
  summarise(AVG_Value = mean(New_Value)) %>% 
  ggplot() + geom_bar(aes(x = State, y = AVG_Value, fill = `Age Group`), stat = "identity", position = "dodge")+ coord_flip()
  
```

```{r}
blank_canvas <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank()
  )

```

```{r}
gg1 <- ggplot(data = states, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(data = tidy_asthma1, 
               aes(fill = AVG_Value)) + scale_fill_distiller(palette = "Spectral") +
  facet_wrap(~`Age Group`) + 
  labs(x = "", y = "", title = "Asthma Prevalence Among Adults 1999 - 2000", 
       fill = "Average %") + theme_minimal() + blank_canvas
```

```{r}
gg2 <- ggplot(data = states, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(data = tidy_asthma2, 
               aes(fill = AVG_Value)) + scale_fill_distiller(palette = "Spectral") +
  facet_wrap(~`Age Group`) + 
  labs(x = "", 
       y = "", 
       title = "Asthma Prevalence Among Adults 2001 - 2002", 
       fill = "Average %") + theme_minimal() + blank_canvas
```
```{r}
gg3 <- ggplot(data = states, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(data = tidy_asthma3, 
               aes(fill = AVG_Value)) + scale_fill_distiller(palette = "Spectral") +
  facet_wrap(~`Age Group`) + 
  labs(x = "", 
       y = "", 
       title = "Asthma Prevalence Among Adults 2003 - 2004", 
       fill = "Average %") +
  theme_minimal( ) + blank_canvas
```
```{r}
gg4 <- ggplot(data = states, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(data = tidy_asthma4, 
               aes(fill = AVG_Value)) + scale_fill_distiller(palette = "Spectral") +
  facet_wrap(~`Age Group`) + 
  labs(x = "", 
       y = "", 
       title = "Asthma Prevalence Among Adults 2005 - 2006", 
       fill = "Average %") + 
  theme_minimal() + blank_canvas
```
```{r}
gg5 <- ggplot(data = states, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(data = tidy_asthma5, 
               aes(fill = AVG_Value)) + scale_fill_distiller(palette = "Spectral") +
  facet_wrap(~`Age Group`) + 
  labs(x = "", 
       y = "", 
       title = "Asthma Prevalence Among Adults 2007 - 2008", 
       fill = "Average %") +
  theme_minimal() + blank_canvas
```
```{r}
gg6 <- ggplot(data = states, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(data = tidy_asthma6, 
               aes(fill = AVG_Value)) + scale_fill_distiller(palette = "Spectral") +
  facet_wrap(~`Age Group`) + 
  labs(x = "", 
       y = "", 
       title = "Asthma Prevalence Among Adults 2009 - 2010", 
       fill = "Average %") + theme_minimal() + blank_canvas
```
```{r}
gg7 <- ggplot(data = states, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(data = tidy_asthma7, 
               aes(fill = AVG_Value)) + scale_fill_distiller(palette = "Spectral") +
  facet_wrap(~`Age Group`) + 
  labs(x = "", 
       y = "", 
       title = "Asthma Prevalence Among Adults 2011 - 2012", 
       fill = "Average %") + theme_minimal() + blank_canvas
```
```{r}
gg8 <- ggplot(data = states, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(data = tidy_asthma8, 
               aes(fill = AVG_Value)) + scale_fill_distiller(palette = "Spectral") +
  facet_wrap(~`Age Group`) + 
  labs(x = "", 
       y = "", 
       title = "Asthma Prevalence Among Adults 2013 - 2014", 
       fill = "Average %") + theme_minimal() + blank_canvas
```
```{r}
gg9 <- ggplot(data = states, mapping = aes(x = long, y = lat, group = group)) + 
  geom_polygon(data = tidy_asthma9, 
               aes(fill = AVG_Value)) + scale_fill_distiller(palette = "Spectral") +
  facet_wrap(~`Age Group`) + 
  labs(x = "", 
       y = "", 
       title = "Asthma Prevalence Among Adults 2015 - 2016", 
       fill = "Average %") + theme_minimal() + blank_canvas
```


```{r}
ggsave(gg1, filename =  "asthma_map2000.png", height = 10, width = 20)
ggsave(gg2, filename =  "asthma_map2002.png", height = 10, width = 20)
ggsave(gg3, filename =  "asthma_map2004.png", height = 10, width = 20)
ggsave(gg4, filename =  "asthma_map2006.png", height = 10, width = 20)
ggsave(gg5, filename =  "asthma_map2008.png", height = 10, width = 20)
ggsave(gg6, filename =  "asthma_map2010.png", height = 10, width = 20)
ggsave(gg7, filename =  "asthma_map2012.png", height = 10, width = 20)
ggsave(gg8, filename =  "asthma_map2014.png", height = 10, width = 20)
ggsave(gg9, filename =  "asthma_map2016.png", height = 10, width = 20)
```

```{r}
billing <- "upbeat-cosine-273900"
#google big query connection
con <- dbConnect(
  bigrquery::bigquery(),
  project = "upbeat-cosine-273900",
  dataset = "epa_historical_air_quality",
  billing = billing
)
con 

epa_download <- dbSendQuery(con, 
                            "SELECT * FROM 
`bigquery-public-data.epa_historical_air_quality.air_quality_annual_summary` 
                            WHERE YEAR >= 2000")
epa_download <- dbFetch(epa_download)
```

```{r} 

#transform data
epa_long <- epa_download %>%
  filter(pollutant_standard %in% c('Ozone 8-hour 2015', 
                                   'PM25 24-hour 2012', 
                                   'CO 8-hour 1971', 
                                   'PM10 24-hour 2006', 
                                   'NO2 Annual 1971', 
                                   'SO2 24-hour 1971')
         | parameter_name %in% c('Average Ambient Temperature',
                                   'Average Ambient Pressure',
                                   'Acceptable PM2.5 AQI & Speciation Mass'))%>%
  filter(completeness_indicator == 'Y') %>%
  mutate(countyFIPs = paste(state_code, county_code, sep =""),
         row_id = paste(countyFIPs,year),
         parameter = paste(parameter_name, "_", sample_duration)) %>%
#remove duplicates
  group_by(parameter_name, row_id) %>%
  arrange(desc(observation_percent)) %>%
  filter(row_number()==1) %>%
  select(countyFIPs,
         row_id,
         parameter_name, 
         year,
        #observation_count,
        #observation_percent,
        # valid_day_count,
        # null_data_count,
         first_max_value,
         arithmetic_mean,
         arithmetic_standard_dev,
         fourth_max_value,
         ninety_nine_percentile,
         fifty_percentile,
        # ten_percentile,
         state_name,
         county_name)
```

